### ISSUE TITLE
No graph opening

### ISSUE THREAD

**Issue by sf8193** [econpy/google-ngrams#12]
Hi, great tool you've made here. 

When I try to plot a graph with the -plot arg, nothing comes up, and the program runs to completion.

my input is this--- python3 getngrams.py einstein, darwin - plot

I'm working on a mac if that makes a difference. Any idea why this would be happening? 

That is when I run it from the command line. I also tried python3 xkcd.py einstein_darwin-eng_2012-1800-2000-3-caseSensitive.csv  after that but nothing from there as well. 

When I call your script from blender(i'm trying to interface my simulation code to make a graph') 

It gives me some errors that look like this

Data saved to Einstein_Darwin-eng_2012-1800-2000-3-caseSensitive.csv
Unable to revert mtime: /Library/Fonts
Unable to revert mtime: /Library/Fonts/Microsoft
Traceback (most recent call last):
  File "google-ngrams/xkcd.py", line 86, in <module>
    plotXKCD(sys.argv[1])
  File "google-ngrams/xkcd.py", line 82, in plotXKCD
    fig.savefig(ngramCSVfile.replace('.csv', '.png'), dpi=190)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/figure.py", line 1421, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/backend_bases.py", line 2220, in print_figure
    **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/backends/backend_agg.py", line 505, in print_png
    FigureCanvasAgg.draw(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/backends/backend_agg.py", line 451, in draw
    self.figure.draw(self.renderer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/artist.py", line 55, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/figure.py", line 1034, in draw
    func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/artist.py", line 55, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py", line 2086, in draw
    a.draw(renderer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/artist.py", line 55, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axis.py", line 1093, in draw
    renderer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axis.py", line 1042, in _get_tick_bboxes
    extent = tick.label1.get_window_extent(renderer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/text.py", line 754, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/text.py", line 320, in _get_layout
    ismath=False)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/text.py", line 312, in get_text_width_height_descent
    *kl, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/backend_bases.py", line 584, in get_text_width_height_descent
    font = self._text2path._get_font(prop)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/textpath.py", line 52, in _get_font
    font = FT2Font(str(fname))
RuntimeError: Could not open facefile Humor-Sans.ttf; Cannot_Open_Resource

so i'm assuming it's something with the font? Have you seen this before?

**Comment by sf8193** [comment]
It was a nonissue. I assumed the file opens on default.
